---
title: "Bike Shares Daily"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    storyboard: true
runtime: shiny    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(readr)
library(tidyverse)
library(lubridate)
library(plotly)
library(knitr)
library(DT)


trips_df <- read.csv("sanfran_bikeshare_joined_oneday.csv")

data_date <- unique(as.Date(trips_df$start_date))
```

Overview
==========================
Column {data-width=650}
-----------------------------------------------------------------------

### Station Usage

```{r}
station_trips_df <- trips_df %>%
  select(start_station_name, end_station_name) %>%
  gather(key = Type, value = Station) %>%
  group_by(Station, Type) %>%
  summarize(n_trips = n()) %>% 
  mutate(Type = ifelse(Type == 'start_station_name', 
                       'Trip Starts', 'Trip Ends')) %>%
  spread(key = Type, value = n_trips) %>%
  replace_na(list(`Trip Starts` = 0, `Trip Ends` = 0)) %>%
  mutate(Gap = `Trip Ends` - `Trip Starts`)

datatable(station_trips_df)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Origins

```{r}
median_min <- median(trips_df$duration_sec / 60) %>% round(digits = 1)
valueBox(median_min,
         caption = "Median Trip Duration (Minutes)",
         icon = 'fa-clock-o')
```

### % Short Trips

```{r}
num_trips <- nrow(trips_df)
short_trips <- sum(trips_df$duration_sec < 600 )
# Under 10 min
pct_short_trips <- round(100 * short_trips / num_trips, 0)

gauge(value = pct_short_trips,
      min = 0,
      max = 100,
      sectors = gaugeSectors(success = c(67,100),
                             warning = c(33,66),
                             danger = c(0,32)))
```


### Trips by Start Time


Trip Duration 
=====================================

```{r}
duration_plot <- trips_df %>%
  mutate(`Trip Duration (min)` = duration_sec / 60) %>%
  ggplot(aes(x = `Trip Duration (min)`)) +
  theme_bw() +
  geom_histogram(binwidth = 1) +
  ylab('# Trips')

duration_plot %>% ggplotly()
```

Maps
======================


Column 
-----------------------------------------------------------------------
### Origins

```{r}

trips_df %>%
  rename(latitude = start_latitude,
         longitude = start_longitude) %>%
  group_by(start_station_id, latitude, longitude) %>%
  count() %>%
  leaflet() %>%
  addTiles() %>%
  addCircles(radius = ~n)

```

> Source: Bay Area Bike Share, Date: `r data_date`

Story {.storyboard}
============

### Most bikes are used only a few times, but a few are used a lot

```{r}
trips_per_bike_df <- trips_df %>%
                        group_by(bike_number) %>%
                        summarize(n_trips = n()) %>%
                        arrange(desc(n_trips))

bike_plot <- trips_per_bike_df %>%
                  ggplot(aes(x = n_trips)) +
                  geom_histogram(binwidth = 1) +
                  ylab('') +
                  xlab('Trips per bike')

ggplotly(bike_plot)
```


### Where did the most used bike go?

```{r}

most_used_bike_df <- trips_df %>%
  filter(bike_number == trips_per_bike_df$bike_number[1])

most_used_bike_df %>%
  rename(latitude = start_latitude,
         longitude = start_longitude) %>%
  group_by(start_station_id, latitude, longitude) %>%
  count() %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers()

```


***

* Bike `r most_used_bike_df$bike_number[1]` made its first trip from `r most_used_bike_df$start_station_name[1]` and ended its day at `r most_used_bike_df$end_station_name[nrow(most_used_bike_df)]`.
* Its longest trip was `r max(most_used_bike_df$duration_sec)/60` minutes long.


Overview_2
===============

```{r include= FALSE}
trips_df <- trips_df %>% mutate(duration_min = duration_sec / 60,
         start_hour = hour(start_date)) %>%
  filter(duration_min <= 8 * 60) # remove trips longer than 8 hours as suspicious data quality

sf_bbox <- c(-123.0137, 37.6040, -122.3549, 37.8324)
sj_bbox <- c(-122.0457, 37.1255, -121.5891, 37.4692)

trips_df <- trips_df %>%
  mutate(city = ifelse((start_latitude >= sf_bbox[2] & start_latitude <= sf_bbox[4]) &
                         (start_longitude >= sf_bbox[1] & start_longitude <= sf_bbox[3]),
                       'San Francisco', ifelse((start_latitude >= sj_bbox[2] & start_latitude <= sj_bbox[4]) &
                                                 (start_longitude >= sj_bbox[1] & start_longitude <= sj_bbox[3]),
                                               'San Jose', 'Other')))
```


Column {data-width=200 .sidebar}
----------------------------------------


```{r}
radioButtons("origin_location", label = "Select trip origin region to display:", 
             choices = c('All' = 'all', 'San Francisco' = 'sf', 'San Jose' = 'sj'), 
             selected = c('all'))

sliderInput("start_slider", 
            label = "Select trip start times to display (hour of day):",
            min = 0, 
            max = 24, 
            value = c(7,10), 
            step = 1,
            dragRange = TRUE)

trips <- reactive({

  if(input$origin_location == 'sf') {
    trips_df <- trips_df %>% filter(city == 'San Francisco' &
                                    start_hour >= input$start_slider[1] &
                                    start_hour <= input$start_slider[2])
  } else if(input$origin_location == 'sj') {
    trips_df <- trips_df %>% filter(city == 'San Jose'&
                                    start_hour >= input$start_slider[1] &
                                    start_hour <= input$start_slider[2])
  }

  trips_df %>%
    filter(start_hour >= input$start_slider[1] &
             start_hour <= input$start_slider[2])

})


```


Column {data-width=450}
--------------------------------------------------

### Origins

```{r}
renderLeaflet({
  trips() %>%
    rename(latitude = start_latitude,
           longitude = start_longitude) %>%
    group_by(start_station_id, latitude, longitude) %>%
    count() %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(radius = ~n)
})
```

Column {data-width=350}
--------------------------------------------------

### Total Trips

```{r}

renderValueBox({
  valueBox(prettyNum(trips() %>%
                       nrow(), big.mark = ','), 
           icon = 'fa-bicycle')
})


# valueBox(prettyNum(nrow(trips_df), big.mark = ','), icon = 'fa-bicycle')
```

### Trips by Start Time

```{r}
renderPlot({
  trips() %>%
    mutate(hour = hour(start_date)) %>%
    group_by(hour) %>%
    summarize(`Trips Started` = n()) %>%
    ggplot(aes(x = hour, y = `Trips Started`)) +
    theme_bw() +
    ylab('Trips Started \n') +
    geom_bar(stat = 'identity') 
})

```

### Trips by Start Time (histogram)

```{r}

sliderInput("duration_bin", 
            label = "Select # of minutes to bin trip durations:",
            min = 1, 
            max = 15, 
            value = 5, 
            step = 1)

renderPlot({trips_df %>%
  mutate(`Trip Duration (min)` = duration_sec / 60) %>%
  ggplot(aes(x = `Trip Duration (min)`)) +
  theme_bw() +
  geom_histogram(binwidth = input$duration_bin) +
  ylab('# Trips')
})
```

